version: '3.9'

services:
  server:
    build: ./
    container_name: TicTacToe_Server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "80:80"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

#To have it serviced from terminal & easily accessible to connection, run as:
#docker-compose run -name <name> --service-ports <service> 
